# Dependencias

FROM node:21-alpine3.19 AS deps

WORKDIR /usr/src/app

COPY package.json ./
COPY package-lock.json ./

RUN npm install

# Builder - Construye la aplicación

FROM node:21-alpine3.19 AS build

WORKDIR /usr/src/app

# Copiar de deps los modulos de node

COPY --from=deps /usr/src/app/node_modules ./node_modules

# Copiar todo el codigo fuente de la aplicación
COPY . .

# Variables de entorno pasadas por el comando de construcción
ARG ORDERS_DATABASE_URL
ENV DATABASE_URL=$ORDERS_DATABASE_URL

# RUN npm run TEST

# Migrar la base de datos
RUN npx prisma migrate deploy

# Generar los archivos de Prisma
RUN npx prisma generate


# RUN npm run BUILD
RUN npm run build

# Limpieza de los modulos que no necesitamos
RUN npm ci -f --only=production && npm cache clean --force



# Crear la imagen final de Docker

FROM node:21-alpine3.19 AS prod

WORKDIR /usr/src/app

# Copiar los modulos de node
COPY --from=build /usr/src/app/node_modules ./node_modules

# Copiar la carpeta de DIST
COPY --from=build /usr/src/app/dist ./dist

# Exponer el puerto
EXPOSE 3000

# Comando para ejecutar la aplicación
CMD ["node", "dist/main.js"]